server:
  shutdown: graceful
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false
  data:
    mongodb:
      auto-index-creation: true
      uuid-representation: standard
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

application:
  version: /v1
  prefix: /api
  project: /mng/cpc
  exclude-prefix-path: springdoc
  role-type: ADMIN
  site-id: 62a15f4ae4129b518b133128

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health

logging:
  level:
    root: ${auth.api.logging.level.root:DEBUG}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${auth.api.logging.level.mongo:DEBUG}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        encryptionsdk: DEBUG

    io:
      spring:
        cloud: INFO

---
server:
  port: 8083
spring:
  config:
    import: classpath:aws-properties.yml, classpath:springdoc.yml
    activate:
      on-profile: local
  data:
    mongodb:
      host: ${auth.mongo.host:localhost}
      port: ${auth.mongo.port:27017}
      database: ${auth.mongo.database:test}
      auto-index-creation: true
      uuid-representation: standard
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
webserver:
  url: http://localhost:3000/
  board-url: https://systems-board.s3.ap-northeast-2.amazonaws.com/

---
server:
  port: 8080
spring:
  config:
    import: classpath:aws-properties-eks-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: eks-dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
webserver:
  url: http://k8s-systemsd-cpcappwe-c3110031ec-598124796.ap-northeast-2.elb.amazonaws.com/
  board-url: https://systems-board.s3.ap-northeast-2.amazonaws.com/

---
server:
  port: 80
spring:
  config:
    import: classpath:aws-properties-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
webserver:
  url: http://bs-dev-cpc-app-web-nlb-ddaac38ef1fa74bf.elb.ap-northeast-2.amazonaws.com/
  board-url: https://bithumb-bs-dev-systems-board.s3.ap-northeast-2.amazonaws.com/

---
server:
  port: 80
spring:
  config:
    import: classpath:aws-properties-qa.yml, classpath:springdoc.yml
    activate:
      on-profile: qa
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
webserver:
  url: http://bs-qa-cpc-app-web-nlb-3bf4d9c2578731b8.elb.ap-northeast-2.amazonaws.com/
  board-url: https://bithumb-bs-dev-systems-board.s3.ap-northeast-2.amazonaws.com/

---
server:
  port: 80
spring:
  config:
    import: classpath:aws-properties-prod.yml
    activate:
      on-profile: prod
springdoc:
  api-docs:
    enabled: false
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
webserver:
  url: https://safe.bithumb.com/
  board-url: https://bithumb-bs-systems-board.s3.ap-northeast-2.amazonaws.com/
