server:
  shutdown: graceful
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false
  data:
    mongodb:
      auto-index-creation: true
      uuid-representation: standard
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

application:
  version: /v1
  prefix: /api
  project: /mng/cpc
  exclude-prefix-path: springdoc

jwt:
  secret: ${cpc.api.jwt.secret:eyJzdWIiOiJtaW5zb3ViQGJpdGh1bWJzeXN0ZW1zLmNvbSIsIm5hbWUiOiJCaXRodW1iU3lzdGVtcyIsImlhdCI6MjA5OTEyMzExMjF9.Lpo86rOQtvBRfVKDGhICUWuZ92rgBIVPM9PVAUiRhAM}

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health

logging:
  level:
    root: ${auth.api.logging.level.root:DEBUG}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${auth.api.logging.level.mongo:DEBUG}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        encryptionsdk: DEBUG

    io:
      spring:
        cloud: INFO

---
server:
  port: 8083
spring:
  config:
    import: classpath:aws-properties.yml, classpath:springdoc.yml
    activate:
      on-profile: local
  data:
    mongodb:
      host: ${auth.mongo.host:localhost}
      port: ${auth.mongo.port:27017}
      database: ${auth.mongo.database:test}
      auto-index-creation: true
      uuid-representation: standard
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml

---
server:
  port: 8080
spring:
  config:
    import: classpath:aws-properties-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml

---
server:
  port: 8080
spring:
  config:
    import: classpath:aws-properties-eks-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: eks-dev
logging:
  config: classpath:logback-spring-dev.xml

---
server:
  port: 8080
spring:
  config:
    import: classpath:aws-properties.yml
    activate:
      on-profile: prod
springdoc:
  api-docs:
    enabled: false
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
